language: java
sudo: false

addons:
  sonarcloud:
    organization: "pantheon-tech"
    token:
      secure: "fArJTxsPIiffE2OX+n8kc5ExbrwfCMh1QoANfi9FDoHrAHOzqsvOZlHUE4k4q5tKJguf+U9/GKw3J8ND0TfGeH9kg6SrtwgY+jya5Ot3SL/nEU6/TOA6+PDKlmE515OIk9B/dLYBzYh/GPr2psDN8YXE0VSGm6SIJwDI/t4tpm9vGvi+Jc3J3qk05zgp8TOcPfawn5C4wLpih7paBtteY1Q+AQds+VzUU4FIENnopEE19J/Prg7QrFNsrp0ckyfFg3luoMjTjIddnZ1VNxYG6R1o42Y086yNGmY91AIY0wKivAYeImZRlPs5icSOJMuO6uuZaNIDgjs8W3mprvEW1XKOjedapavuATGA/tdKnr27L+/JM22ECh89nTrBMeWWE+yGg3jt6MeAlMGJXjPXKF9nzrzjopcP2zqW/uWLRdjGmKmKjrarYHk3HilO/wwkbrzGri4h6f5TJmXBpAvSoJ35IDc3rf736csyklhyp6Fpkk9tD2JHWeViP2HItmYGWjsx0W5AqX2AJo+OYpS1IX7mKPM1lSrzfcdstE73AH4qCcUxayy7sZEjrJA52Mx7WnauMBq9EjNKsd8U4pCzdDjMO36CUCniBV9vH6ofIatYRHNhOCmFU+rqwj3KsViC72Dmhvtvg0rkceMZBoczpSRUSXoVdLvcGU0l48iT0RU="

jdk:
  - oraclejdk8

before_install:
  - wget https://raw.githubusercontent.com/opendaylight/odlparent/master/settings.xml; cp ./settings.xml $HOME/.m2/settings.xml
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version | grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
script:
  - mvn clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
  provider: releases
  api_key:
    secure: UYIc86RcVfqm1xJbX6TSyZ3lG7+0Ih5hLTSdabKjmfTrvM26VZlbcDmGFD4sguRci0il1ULln7P3pFo5zqNnWY9chTCFAPdj9zl+mynHwgIFfs2yK+I5l9oHg/thRK+DE937YUOcNrXBrwiDlb6r8h2oILPJwhPDZUHe27yC5FzusA8FflrJupwD7IQdAEdGlcIWBR9BKv/cljNBYxhrc8p8EM4VP5nihdDVxWD52kelEpllDJIY6sj9sE/pxLoxMHYgbvnta/MG038h6u1yMqXl37XR2SjSkmq7aAeIPr2+FhDy3MM6raxb7xeGScAlFmeVuPIdYMvoLsEMY+GAAUABWYPx5oG8wDx61SyM1P7Mm8dvXKIkk8UfrRbqWtnHmNjFcU1Nz6WdyGg4VjPjRAxK1vYMuU4dNh4nVdmYBFSFgosUjGw2Hd6TWeioEbvzVXjqLek6hf6FRtazF9y4qbb3qqassyzpUm3IqNjJOGH9klFUFHJM7sKmRdltZj3XLoqU7VYkfx1du5EJnViaPSEX2ygJ7jxzxKGbPH9JucJuGUavRivDCG08lP4J677xM0RQxR89t4CHX6lH2l103HwcWoO+jAS/egAKLR8G+sVPa7OJj6Emj1kTbOvVMzxlWjR18UIFtNW5FPL91NN9o+mLwVQ1Yn4sesv+oTT3I+0=
  file:
    - triemap/target/triemap-$project_version.jar
  skip_cleanup: true
  on:
    repo: PantheonTechnologies/triemap
  name: $project_version
after_success:
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report
